name: Angular CI Pipeline

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  test_and_build:
    uses: Rite-Technologies-23/reusable-repo-flutter/.github/workflows/reusable_angular_ci_pipeline.yml@main
    with:
      node_version: ${{ vars.NODE_VERSION }}
      coverage_threshold: ${{ vars.COVERAGE_THRESHOLD }}
      project_path: '.'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
